### ISSUE TITLE
Build/Dependency issue

### ISSUE THREAD

**Issue by dr-kino** [hatchbed/log_view#13]
Hi, congrats on this pretty nice project, I was looking for text-based log viewer and I found your project. My issue is to find the right dependencies to build it.

After install catkin and rosscpp, I am still getting an error "Could not find the required component 'roscpp'"

Installation commands on ubuntu distro:
apt install catkin
apt install ros-noetic-roscpp

**Comment by malban** [comment]
The binary version should be available through apt with the standard ROS source list: http://wiki.ros.org/noetic/Installation/Ubuntu#Installation.2FUbuntu.2FSources.Setup_your_sources.list

```
sudo apt install ros-noetic-log-view
```

To build it from source, it's the same as any ROS1 package.  I usually use [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/) because it is more friendly than straight catkin.

1. Follow the Ubuntu ROS instructions linked above to install base ROS packages.
2. Install and initialize rosdep: http://wiki.ros.org/rosdep
3. Install catkin_tools: 
```
$ python3 -m pip install catkin-tools
```
4. Create a catkin workspace with the package 
```
$ mkdir -p ~/catkin_ws/src
$ cd ~/catkin_ws
$ catkin init
$ catkin config --extend /opt/ros/noetic
$ catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
$ git clone https://github.com/hatchbed/log_view.git src/log_view
```
5. Install dependencies
```
$ rosdep install --from-paths src --ignore-src
```
6. Build
```
$ catkin build
```
7. Run
```
$ source devel/setup.bash
$ rosrun log_view log_viewer
```

**Comment by dr-kino** [comment]
Thank you very much @malban ! I was not used to using ROS. I will install those packets point by you!

**Comment by dr-kino** [comment]
All the procedures pointed out above worked. Thanks for your support!
